-- Supabase table schema for DigitalSaathi client reviews

create table if not exists reviews (
  id bigint generated by default as identity primary key,
  client_name text not null,
  business_name text not null,
  rating int not null check (rating between 1 and 5),
  review text not null,
  status text not null default 'pending' check (status in ('pending', 'approved')),
  created_at timestamptz not null default now()
);

create index if not exists idx_reviews_status on reviews (status);
create index if not exists idx_reviews_created_at on reviews (created_at desc);
